### ISSUE TITLE
SB4 + Vistas

### ISSUE THREAD

**Issue by BahaDuoc** [Negusun/hotel_ids#4]
**SB4**

Eliminar Reserva
Registrar Pago
Actualizar Pago
Eliminar Pago

Más vistas asociadas al _sprint_ junto con las vistas pendientes.

**Comment by Negusun** [comment]
por favor reconsiderar lo de los pagos si en el diagrama de entidad relación ni siquiera tenemos una entidad de pagos @BahaDuoc
