### ISSUE TITLE
SB5 y proyecto terminado

### ISSUE THREAD

**Issue by ghost** [Negusun/hotel_ids#5]
SB5 compuesto por:

**Terminar todas las vistas
Generar Reportes Hotel
Generar Reportes Habitación
Generar Reportes Reserva**
Generar Reportes Pago
Último requerimiento

Considerando que Ignacio Villaroel no dio el último requerimiento y Generar Reportes Pago es una operación relacionada con el cuarto módulo, realizar el resto.

saludos

**Comment by Negusun** [comment]
agregado autenticacion de usuarios se pueden ver las reservas del usuario autenticado

el software va a tirar errores en las siguientes funcionalidades:

- registrar usuario
- reiniciar password
- recuperar password
- activar usuario
- cambiar password

motivo se debe configurar un servidor smpt para enviar los correos al usuario aun asi la activación se puede hacer manual a través del panel de administración

EDIT: Si necesitan hacer cambios o agregar mas cosas pedirlas a ricardo o carlos o cualquiera que sea programador tengo que repasar para seguridad y bd
